# This example uses rpm-ostree's cliwrap to allow dracut to run on the container and generate an initramfs.
FROM localhost/silverblue:latest

# Install the NVIDIA driver.
COPY --from=ghcr.io/ublue-os/akmods-nvidia-open:main-40 /rpms/ /tmp/rpms
RUN find /tmp/rpms
RUN rpm-ostree install /tmp/rpms/ublue-os/ublue-os-nvidia*.rpm
RUN rpm-ostree install /tmp/rpms/kmods/kmod-nvidia*.rpm


# Add the modprobe config file
RUN wget -O /etc/modprobe.d/nvidia.conf https://raw.githubusercontent.com/funkemunky/fedora-images/refs/heads/main/fedora-silverblue-nvidia/nvidia.conf && \
 ostree container commit
