# This example uses rpm-ostree's cliwrap to allow dracut to run on the container and generate an initramfs.
FROM ghcr.io/funkemunky/fedora-images/fedora-silverblue:41

# Install the NVIDIA driver.
RUN rpm-ostree cliwrap install-to-root / && rpm-ostree install kernel akmod-nvidia xorg-x11-drv-nvidia-cuda && \
 ostree container commit

# Add the modprobe config file
RUN wget -O /etc/modprobe.d/nvidia.conf https://raw.githubusercontent.com/funkemunky/fedora-images/refs/heads/main/fedora-silverblue-nvidia/nvidia.conf && \
 ostree container commit