# This example uses rpm-ostree's cliwrap to allow dracut to run on the container and generate an initramfs.
FROM localhost/fedora-silverblue:41

# Enable cliwrap.
RUN rpm-ostree cliwrap install-to-root /

# Install the NVIDIA driver.
RUN rpm-ostree install akmod-nvidia xorg-x11-drv-nvidia-cuda && \
 rpm-ostree kargs --append=rd.driver.blacklist=nouveau --append=modprobe.blacklist=nouveau --append=nvidia-drm.modeset=1 && \
 ostree container commit