# This example uses rpm-ostree's cliwrap to allow dracut to run on the container and generate an initramfs.
FROM nexus.funkemunky.cc/fedora/fedora-kinoite:40

# Installing RPM-Fusion Repositories
RUN rpm-ostree cliwrap install-to-root / && \
rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
ostree container commit

# Installing Mesa VA Drivers
RUN rpm-ostree override remove mesa-va-drivers --install mesa-va-drivers-freeworld \
--install mesa-vdpau-drivers-freeworld

# Installing GStreamer Plugins
RUN rpm-ostree install gstreamer1-plugin-libav gstreamer1-plugins-bad-free-extras \
gstreamer1-plugins-bad-freeworld gstreamer1-plugins-ugly gstreamer1-vaapi

# Installing FFmpeg
RUN rpm-ostree override remove ffmpeg-free libavdevice-free libavcodec-free libavfilter-free libavformat-free libavutil-free \
libpostproc-free libswresample-free libswscale-free --install ffmpeg && \
ostree container commit

# Installing various tools and apps
RUN rpm-ostree install distrobox nextcloud-client