# This example uses rpm-ostree's cliwrap to allow dracut to run on the container and generate an initramfs.
FROM nexus.funkemunky.cc/fedora/fedora-kinoite:40

# Install the NVIDIA driver.
COPY --from=ghcr.io/ublue-os/akmods-nvidia-open:main-40 /rpms/ /tmp/rpms

# Installing RPM-Fusion Repositories
RUN rpm-ostree cliwrap install-to-root / && \
find /tmp/rpms && \
rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
ostree container commit && \
rpm-ostree override remove mesa-va-drivers --install mesa-va-drivers-freeworld \
--install mesa-vdpau-drivers-freeworld && rpm-ostree install gstreamer1-plugin-libav gstreamer1-plugins-bad-free-extras \
gstreamer1-plugins-bad-freeworld gstreamer1-plugins-ugly gstreamer1-vaapi && rpm-ostree override remove ffmpeg-free libavdevice-free libavcodec-free libavfilter-free libavformat-free libavutil-free \
libpostproc-free libswresample-free libswscale-free --install ffmpeg && \
rpm-ostree install /tmp/rpms/ublue-os/ublue-os-nvidia*.rpm && rpm-ostree install /tmp/rpms/kmods/kmod-nvidia*.rpm && \
rpm-ostree install distrobox nextcloud-client && rm /usr/share/applications/com.nextcloud.desktopclient.nextcloud.desktop && \
curl https://pastebin.com/raw/9gsw3HRT > /etc/modprobe.d/nvidia.conf && ostree container commit

RUN curl https://pastebin.com/raw/9gsw3HRT > /etc/modprobe.d/nvidia.conf && ostree container commit