# This example uses rpm-ostree's cliwrap to allow dracut to run on the container and generate an initramfs.
FROM ghcr.io/funkemunky/fedora-images/fedora-kinoite:40

# Install the NVIDIA driver.
COPY --from=ghcr.io/ublue-os/akmods-nvidia-open:main-40 /rpms/ /tmp/rpms
COPY --from=ghcr.io/ublue-os/akmods:main-40 /rpms/tmp/rpms
RUN find /tmp/rpms && \
rpm-ostree install /tmp/rpms/ublue-os/ublue-os-nvidia*.rpm /tmp/rpms/ublue-os/ublue-os-akmods*.rpm && rpm-ostree install /tmp/rpms/kmods/kmod-nvidia*.rpm /tmp/rpms/ublue-os/kmod-openrazer*.rpm && \
curl https://pastebin.com/raw/9gsw3HRT > /etc/modprobe.d/nvidia.conf && \
          ostree container commit
