# This example uses rpm-ostree's cliwrap to allow dracut to run on the container and generate an initramfs.
FROM quay.io/fedora/fedora-silverblue:41

# Install the new kernel.
RUN rpm-ostree cliwrap install-to-root / && \
rpm-ostree override replace https://kojipkgs.fedoraproject.org/packages/kernel/6.10.13/200.fc40/x86_64/kernel-6.10.13-200.fc40.x86_64.rpm \
https://kojipkgs.fedoraproject.org/packages/kernel/6.10.13/200.fc40/x86_64/kernel-core-6.10.13-200.fc40.x86_64.rpm \
https://kojipkgs.fedoraproject.org/packages/kernel/6.10.13/200.fc40/x86_64/kernel-modules-6.10.13-200.fc40.x86_64.rpm \
https://kojipkgs.fedoraproject.org/packages/kernel/6.10.13/200.fc40/x86_64/kernel-modules-extra-6.10.13-200.fc40.x86_64.rpm \
https://kojipkgs.fedoraproject.org/packages/kernel/6.10.13/200.fc40/x86_64/kernel-modules-core-6.10.13-200.fc40.x86_64.rpm \
https://kojipkgs.fedoraproject.org/packages/kernel/6.10.13/200.fc40/x86_64/kernel-devel-6.10.13-200.fc40.x86_64.rpm \
https://kojipkgs.fedoraproject.org/packages/kernel-headers/6.10.3/200.fc40/x86_64/kernel-headers-6.10.3-200.fc40.x86_64.rpm \
https://kojipkgs.fedoraproject.org/packages/kernel/6.10.13/200.fc40/x86_64/kernel-devel-matched-6.10.13-200.fc40.x86_64.rpm && \
ostree container commit

# Installing RPM-Fusion Repositories
RUN rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && gnome-tweaks && \
ostree container commit && \
rpm-ostree override remove mesa-va-drivers --install mesa-va-drivers-freeworld --install mesa-vdpau-drivers-freeworld && \
rpm-ostree install gstreamer1-plugins-bad-free-extras gstreamer1-plugins-bad-freeworld gstreamer1-plugins-ugly gstreamer1-vaapi && \
ostree container commit && \
rpm-ostree override remove ffmpeg-free libavdevice-free libavcodec-free libavfilter-free libavformat-free libavutil-free libpostproc-free libswresample-free libswscale-free --install ffmpeg && \
ostree container commit
