# This example uses rpm-ostree's cliwrap to allow dracut to run on the container and generate an initramfs.
FROM ghcr.io/funkemunky/fedora-images/fedora-silverblue:41

# Install the NVIDIA driver.
COPY --from=ghcr.io/ublue-os/akmods-nvidia-open:main-40 /rpms/ /tmp/rpms
RUN find /tmp/rpms
RUN rpm-ostree install /tmp/rpms/ublue-os/ublue-os-nvidia*.rpm
RUN rpm-ostree install /tmp/rpms/kmods/kmod-nvidia*.rpm


# Add the modprobe config file
RUN echo "blacklist nouveau\n\
          options nvidia-drm modeset=1\n\
          \n\
          # Enable DynamicPowerManagement\n\
          # http://download.nvidia.com/XFree86/Linux-x86_64/440.31/README/dynamicpowermanagement.html\n\
          options nvidia NVreg_DynamicPowerManagement=0x03" > /etc/modprobe.d/nvidia.conf && \
          ostree container commit