# This example uses rpm-ostree's cliwrap to allow dracut to run on the container and generate an initramfs.
FROM quay.io/fedora/fedora-silverblue:41

RUN curl https://kojipkgs.fedoraproject.org/packages/kernel/6.10.14/200.fc40/x86_64/kernel-6.10.14-200.fc40.x86_64.rpm && \
    curl https://kojipkgs.fedoraproject.org/packages/kernel/6.10.14/200.fc40/x86_64/kernel-core-6.10.14-200.fc40.x86_64.rpm && \
    curl https://kojipkgs.fedoraproject.org/packages/kernel/6.10.14/200.fc40/x86_64/kernel-modules-6.10.14-200.fc40.x86_64.rpm && \
    curl https://kojipkgs.fedoraproject.org/packages/kernel/6.10.14/200.fc40/x86_64/kernel-modules-extra-6.10.14-200.fc40.x86_64.rpm && \
    curl https://kojipkgs.fedoraproject.org/packages/kernel/6.10.14/200.fc40/x86_64/kernel-devel-6.10.14-200.fc40.x86_64.rpm

# Replace the kernel, kernel-core, kernel-modules-core and kernel-modules packages.
RUN rpm-ostree override remove kernel kernel-{core,modules,modules-extra} \
    --install kernel-6.10.14-200.fc40.x86_64.rpm \
    --install kernel-core-6.10.14-200.fc40.x86_64.rpm \
    --install kernel-modules-6.10.14-200.fc40.x86_64.rpm \
    --install kernel-modules-extra-6.10.14-200.fc40.x86_64.rpm \
    --install kernel-devel-6.10.14-200.fc40.x86_64.rpm && \
    ostree container commit
