name: Build Fedora Silverblue Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache APT packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman podman-docker

      - name: Cache Podman image layers
        uses: actions/cache@v3
        with:
          path: /var/lib/containers/storage
          key: ${{ runner.os }}-podman-layers
          restore-keys: |
            ${{ runner.os }}-podman-layers


      - name: Find and build Containerfiles
        run: |
          find . -name 'Containerfile' | while read containerfile; do
            dir=$(dirname "$containerfile")
            package_name=$(basename "$dir")
            echo "PACKAGE_NAME=$package_name" >> $GITHUB_ENV
          done

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.PACKAGE_NAME }}/Containerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.PACKAGE_NAME }}:latest

      - name: Get package ID
        run: |
          PACKAGE_ID=$(podman run --rm ghcr.io/${{ github.repository }}/${{ env.PACKAGE_NAME }}:latest rpm -q kernel-longterm)
          echo "PACKAGE_ID=$PACKAGE_ID" >> $GITHUB_ENV
          echo "Package ID: $PACKAGE_ID" > ${{ env.PACKAGE_NAME }}/package_id.txt
          git add ${{ env.PACKAGE_NAME }}/package_id.txt

      - name: Commit updated package IDs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update package IDs"
          git push origin main
        env:
          PACKAGE_ID: ${{ env.PACKAGE_ID }}