name: Build Kinoite

on:
  workflow_dispatch:

jobs:
  build-kinoite-nvidia:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push fedora-kinoite-nvidia variant
        uses: redhat-actions/podman-build-push@v2
        with:
          context: .
          file: fedora-kinoite/nvidia/Containerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/fedora-kinoite:41-nvidia
            ghcr.io/${{ github.repository }}/fedora-kinoite:latest-nvidia
