name: Build Fedora Silverblue Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Podman installation
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/podman
          key: ${{ runner.os }}-podman

      - name: Install Podman
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Cache Podman installation
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/podman
          key: ${{ runner.os }}-podman

      - name: Install Podman
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get -y install podman