name: Build Fedora Silverblue Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *' # 2:00 AM EST (7:00 AM UTC)

jobs:
  build-silverblue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push fedora-silverblue
        uses: docker/build-push-action@v4
        with:
          context: .
          file: fedora-silverblue/Containerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/fedora-silverblue:41
            ghcr.io/${{ github.repository }}/fedora-silverblue:latest
  build-kinoite:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push fedora-kinoite
        uses: docker/build-push-action@v4
        with:
          context: .
          file: fedora-kinoite/Containerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/fedora-kinoite:40
            ghcr.io/${{ github.repository }}/fedora-kinoite:latest
  build-silverblue-nvidia:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push fedora-silverblue-6.10 variant
        uses: docker/build-push-action@v4
        with:
          context: .
          file: fedora-silverblue/nvidia/Containerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/fedora-silverblue:41-nvidia
            ghcr.io/${{ github.repository }}/fedora-silverblue:latest-nvidia
  build-silverblue-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push fedora-silverblue-6.10 variant
        uses: docker/build-push-action@v4
        with:
          context: .
          file: fedora-silverblue/custom-kernel/Containerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/fedora-silverblue:41-6.10
            ghcr.io/${{ github.repository }}/fedora-silverblue:latest-6.10
  build-kinoite-nvidia:
    runs-on: self-hosted
    needs: build-kinoite

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push fedora-kinoite-nvidia variant
        uses: docker/build-push-action@v4
        with:
          context: .
          file: fedora-kinoite/nvidia/Containerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/fedora-kinoite:40-nvidia
            ghcr.io/${{ github.repository }}/fedora-kinoite:latest-nvidia