name: Build Nvidia Variant Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache APT packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Cache Podman image layers
        uses: actions/cache@v3
        with:
          path: /var/lib/containers/storage
          key: ${{ runner.os }}-podman-layers
          restore-keys: |
            ${{ runner.os }}-podman-layers

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push fedora-silverblue-nvidia variant
        uses: docker/build-push-action@v4
        with:
          context: .
          file: fedora-silverblue-nvidia/Containerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/fedora-silverblue-nvidia:41