name: Build Fedora Silverblue Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Build and push Podman image
        run: |
          podman build -t ghcr.io/${{ github.repository }}/fedora-silverblue:latest ./lts-kernel
          echo ${{ secrets.GITHUB_TOKEN }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin
          podman push ghcr.io/${{ github.repository }}/fedora-silverblue:latest

      - name: Update package ID
        run: |
          PACKAGE_ID=$(podman run --rm ghcr.io/${{ github.repository }}/fedora-silverblue:latest rpm -q kernel-longterm)
          echo "PACKAGE_ID=$PACKAGE_ID" >> $GITHUB_ENV

      - name: Commit updated package ID
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo "Package ID: $PACKAGE_ID" > package_id.txt
          git add package_id.txt
          git commit -m "Update package ID"
          git push origin main
        env:
          PACKAGE_ID: ${{ env.PACKAGE_ID }}