name: Build Kinoite

on:
  workflow_dispatch:

jobs:
  build-kinoite-nvidia:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push fedora-kinoite-nvidia variant
        uses: redhat-actions/buildah-build@v2
        with:
          context: .
          containerfiles: fedora-kinoite/nvidia/Containerfile
          image: ghcr.io/${{ github.repository }}/fedora-kinoite:41-nvidia
          tags: |
            ghcr.io/${{ github.repository }}/fedora-kinoite:41-nvidia
            ghcr.io/${{ github.repository }}/fedora-kinoite:latest-nvidia
          cache-from: type=gha
          cache-to: type=gha,mode=max
