name: Build Fedora Silverblue Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Podman installation
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/podman
          key: ${{ runner.os }}-podman

      - name: Install Podman
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Find and build Containerfiles
        run: |
          find . -name 'Containerfile' | while read containerfile; do
            dir=$(dirname "$containerfile")
            package_name=$(basename "$dir")
            podman build -t ghcr.io/${{ github.repository }}/$package_name:latest "$dir"
            echo ${{ secrets.GITHUB_TOKEN }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin
            podman push ghcr.io/${{ github.repository }}/$package_name:latest
            PACKAGE_ID=$(podman run --rm ghcr.io/${{ github.repository }}/$package_name:latest rpm -q kernel-longterm)
            echo "PACKAGE_ID=$PACKAGE_ID" >> $GITHUB_ENV
            echo "Package ID: $PACKAGE_ID" > "$dir/package_id.txt"
            git add "$dir/package_id.txt"
          done

      - name: Commit updated package IDs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update package IDs"
          git push origin main
        env:
          PACKAGE_ID: ${{ env.PACKAGE_ID }}